export const ERROR_CODE = {
  HTTP_ERROR: 'HTTP_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_IDENTIFIER: 'INVALID_IDENTIFIER',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AUTH_EMAIL_IN_USE: 'AUTH_EMAIL_IN_USE',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCESS_REQUIRED: 'AUTH_ACCESS_REQUIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PET_NOT_FOUND: 'PET_NOT_FOUND',
  PET_ACCESS_DENIED: 'PET_ACCESS_DENIED',
  PET_ROLE_FORBIDDEN: 'PET_ROLE_FORBIDDEN',
  PET_INVALID_BIRTH_DATE: 'PET_INVALID_BIRTH_DATE',
  PET_ACCESS_EXISTS: 'PET_ACCESS_EXISTS',
  PET_ACCESS_NOT_FOUND: 'PET_ACCESS_NOT_FOUND',
  PET_LAST_OWNER: 'PET_LAST_OWNER',
  VACCINATION_NOT_FOUND: 'VACCINATION_NOT_FOUND',
  VACCINATION_INVALID_DATES: 'VACCINATION_INVALID_DATES',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
